baseURL: https://estadistica-1-mdr-2022.netlify.app/
title: ASAS
theme: bigspring-light
paginate: '3'
summaryLength: '15'
disqusShortname: 'https-statistics-1-mdr-netlify-app'
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
