baseURL: https://estadistica2022-mdr.netlify.app/
title: Estadística
theme: bigspring-light
paginate: '3'
summaryLength: '15'
disqusShortname: 'https-statistics-1-mdr-netlify-app'
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
