# main menu
[[main]]
name = "Bienvenido"
url = "/"
weight = 1

[[main]]
name = "Sesiones"
url = "blog/"
weight = 2

[[main]]
name = "Ejercicios"
url = "jupyternb/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

[[main]]
name = "Bibliografia"
url = "Referencias/"
weight = 5

[[main]]
name = "Temario"
url = "Programa/"
weight = 6


# footer menu left
[[footer_left]]
name = "Documentación sobre R"
url = "Rbooks/"

[[footer_left]]
name = "Casos de estudio"
url = "Ejemplos/"

[[footer_left]]
name = "Jupyter notebooks"
url = "Jupyternb/"


# footer menu middle

[[footer_middle]]
name = "Tutoriales"
url = "Videos/"



# footer menu right
[[footer_right]]
name = "Programa"
url = "Programa/"

[[footer_right]]
name = "Calendario de sesiones"
url = "Calendario/"

[[footer_right]]
name = "Reglas de Evaluación "
url = "Evaluación/"