#################### default parameters ################################
logo = "images/logo1.png"
logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo1.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "https://formspree.io/f/xvolrokq" # contact form works with https://formspree.io

# Type of pages to be rendered with a blog view
blogCategoryType = "category"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[navigation_button]
enable = true
label = "Agendar tutoria"
link = "contact"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"
  
############################# social site ########################
[[social]]
title = "José Luis at El Colef"
icon = "fab fa-creative-commons-share" # themify icon : https://themify.me/themify-icons
link = "https://www.colef.mx/posgrado/profesores/jose-luis-manzanares-rivera/"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/JLManzanaresR"

[[social]]
title = "Your teacher academic credentials"
icon = "fab fa-ello" # themify icon : https://themify.me/themify-icons
link = "https://joseluismanzanaresrivera.github.io/profile/index.html"

[[social]]
title = "Real data analysis project hub"
icon = "fab fa-deezer" # themify icon : https://themify.me/themify-icons
link = "https://insight4health.netlify.app/"